### ISSUE TITLE
Never leaves configuration mode.

### ISSUE THREAD

**Issue by chris-edwards-pub** [emanuelelaface/USBtoC64#1]
I booted into configuration mode, then insert mouses USB and the green light just stays on.  Never turns off.  Any ideas?

**Comment by emanuelelaface** [comment]
hi, so if I understood correctly, you started the board, when there is the red light you hold the B button, the red led flashes and then you have the green led on. Now you insert the USB joystick/gamepad and nothing happens, am I right?

**Comment by chris-edwards-pub** [comment]
Thanks!  I was trying to configure the mouse.  BTW, the mouse work perfect.

**Comment by emanuelelaface** [comment]
perfect, thanks for the check!
